version: "3.9"
name: boilerplate-angular-19


services:
  # Serviço para o app
  angular-app:
    image: boilerplate-angular-19
    container_name: boilerplate-angular-19-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:80"
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Serviço para o banco de dados MySQL
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3100:3306"
    restart: unless-stopped

  # Serviço para api
  laravel-api:
    image: php:8.0-apache
    container_name: boilerplate-laravel-10-api
    build:
      context: ./laravel
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "3200:80"
    depends_on:
      - mysql-db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
    restart: unless-stopped

volumes:
  mysql-data:
