version: "3.9"

services:
  angular-app:
    image: boilerplate
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:80"
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    restart: unless-stopped
